### ISSUE TITLE
UGREEN AX1800 USB WLAN Stick Adapter WiFi 6 USB 3.0 Adapter (0bda:b832) - boot issues

### ISSUE THREAD

**Issue by kuhnchris** [morrownr/rtl8852bu#35]
Hello!

First of all, thanks for keeping track of the driver(s), as owner of various RTL dongles (willingly or not) i know what hassle it is to hunt and track down all the various drivers.

I recently purchased a "UGREEN AX1800 USB WLAN Stick Adapter WiFi 6 USB 3.0 Adapter for PC Dual 5dBi WLAN Antennas with Built-in Driver, Super Wall Penetration and Dual Band (5GHz/2.4GHz) for Windows 10/11" (https://www.amazon.de/-/en/dp/B0CJ9G9Y4K), turns out it's actually a RTL8852BU-compatible device, who knew.
Anyways, basically, with this driver, everything works fine, 5GHZ network works properly, speeds saturate my connection, all's fine.
BUT. Due to the initial state of the device (it pops up as a CDROM device) the boot process currently get stuck whenever I reboot the machine. This is not desirable. I do see some suggestions of "removing a resistor on the board to fix the inital cdrom state" - so I wonder if this information is floating around somewhere here - if it helps I can take screenshots of the PCB to figure this out, if anyone got any info regarding that, I'd be glad to hear.

**Note: It actually get stuck twice during boot, once directly after loading the kernel into memory (post-grub) indefinitly, and then, afterwards, it gets stuck when udev is enumerating the devices. Unplugging the device makes it continue booting, replugging simply puts it into CDROM mode, which can easily be fixed with `usb_modeswitch -RWK -v 0bda -p 1a2b`. Interesting thing here tho, is, that the device does *not* react properly on the eject, i.e. it hangs for a while until it suddenly springs to life again and switches into 8852BU mode (ID 0bda:b832 Realtek Semiconductor Corp. 802.11ac WLAN Adapter).

Thanks!

**Comment by morrownr** [comment]
@kuhnchris 

> as owner of various RTL dongles...

We are currently working to upstream some new WiFi 5 Realtek drivers in the kernel. We have also been working to improve the Realtek WiFi 5 drivers that are in the kernel. We could use some help testing. If you have time, run the following on each of your older adapters and paste the line that shows your adapters:

$ lsusb

That will help me know what you have and I can direct you to the appropriate site.

Regarding your "UGREEN AX1800 USB", my advice is for you to return it to get your money back.

Here is a post I made recently in Issues at the Main Menu:

https://github.com/morrownr/USB-WiFi/issues/449

The Main Menu gives a lot of good advice. Here is the link. The first 3 menu items help users determine what to buy:

https://github.com/morrownr/USB-WiFi

I wish I had better news but maybe you can send the adapter back. Keeping it will likely lead to years of pure aggrivation which is unnecessary since there are many really good usb wifi adapters that work on Linux in a plug and play manner.

@morrownr

**Comment by kuhnchris** [comment]
Hello,

yeah, I was aware of the return window still accepting it back, also I'm aware of your main menu, i just needed something to test if my home-made AP was the issue or my built-in intel wifi card, didn't look too hard, and regretted it being the RTL one ;-) I will probabbly look around if I can find something more suitable for my needs, thanks for checking in tho! :-)

Ad upstream work: wow, that's great! I don't have many *wifi 5* dongles per-se, only a ton of "old" ones. I assume I won't be of much help, but just in case something check-worthy is around, attached you see my little extra hub with the sticks I found laying around (i still probabbly have a couple more but they are spread wide across my dungeon, but I see some I'll add them to the list).

Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 05e3:0608 Genesys Logic, Inc. Hub
Bus 001 Device 003: ID 8087:0aa7 Intel Corp. Wireless-AC 3168 Bluetooth
Bus 001 Device 005: ID 1462:7d14 Micro Star International MYSTIC LIGHT 
Bus 001 Device 006: ID 258a:002a SINO WEALTH Gaming KB 
Bus 001 Device 007: ID 046d:c52b Logitech, Inc. Unifying Receiver
Bus 001 Device 008: ID 3142:0001 FIFINE Microphones FIFINE K670 Microphone
Bus 001 Device 009: ID 0bda:5411 Realtek Semiconductor Corp. RTS5411 Hub
Bus 001 Device 010: ID 0bda:5411 Realtek Semiconductor Corp. RTS5411 Hub
Bus 001 Device 011: ID 0846:6a00 NetGear, Inc. WG111v2 54 Mbps Wireless [RealTek RTL8187L]
Bus 001 Device 012: ID 1ea7:0064 SHARKOON Technologies GmbH 2.4GHz Wireless rechargeable vertical mouse [More&Better]
Bus 001 Device 013: ID 0e8d:7961 MediaTek Inc. Wireless_Device
Bus 001 Device 014: ID 0bda:8179 Realtek Semiconductor Corp. RTL8188EUS 802.11n Wireless Network Adapter
Bus 001 Device 015: ID 15a4:1001 Afatech Technologies, Inc. AF9015/AF9035 DVB-T stick
Bus 001 Device 016: ID 0bda:8176 Realtek Semiconductor Corp. RTL8188CUS 802.11n WLAN Adapter
Bus 001 Device 017: ID 2001:3319 D-Link Corp. DWA-131 Wireless N Nano Adapter (Rev. E1) [Realtek RTL8192EU]
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 002: ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 005 Device 003: ID 0bda:b832 Realtek Semiconductor Corp. 802.11ac WLAN Adapter

Again, thanks for checking in, and keep up the good work! :+1: 
Chris

**Comment by morrownr** [comment]
> Bus 001 Device 013: ID 0e8d:7961 MediaTek Inc. Wireless_Device

Hmmm... that is a mt7921au chip based adapter that should work well with any distro using kernel 5.19 or later. It is WiFi 6 and tri-band. The rest of the adapters are older WiFi 4 adapters. This site concentrates on WiFi 5 and later... basically, what can users readily buy as new right now.

I can help you, when I have time, to try to solve that specific multi-state issue, but if you can get your money back, do it because that adapter will be frustrating for a long time for many reasons.

**Comment by kuhnchris** [comment]
Thanks for checking, I'll just keep it as a cautious tale for others to avoid buying if possible :-)

**Comment by kuhnchris** [comment]
I'm just leaving this here for future references (since my return window sadly passed before I could return it): 

https://www.draisberghof.de/usb_modeswitch/bb/viewtopic.php?f=4&t=3055&p=20078#p20078
found via:
https://linux.brostrend.com/advanced/usb_modeswitch/

the magic words being:
`GRUB_CMDLINE_LINUX_DEFAULT="usb-storage.quirks=0bda:1a2b:i"` in `/etc/default/grub` (+ update-grub, don't forget that!)

(yes, funnily enough i purchased an FENVI WIFI 6 Adapter AX286 "stick", which works fine in WIFI6 mode, and *afterwards* found this about quirks from a unrelated page that provides the driver for the AX stick...)

Basically this (should) disable the kernel interacting with the SCSI/"CDROM" mode of the device, leaving us with a functional kernel booting in regular-time. (aside from udev-rule a usb_modechange)

Here are some pictures of the board - sadly it's a multi-layer board, so aside from ripping off the storage device in the top left in the first picture (the SPI flash containing the cdrom data) not much I can do, except for aggregating the issue by ripping off the flash or do some trolling with it. :
![image](https://github.com/user-attachments/assets/9bebc603-1f5f-4e60-89cb-c2533d961203)
![image](https://github.com/user-attachments/assets/a88be895-bc3f-4d82-9167-119dfbbace09)
