### ISSUE TITLE
Inclusion of Zyxel NWD7605

### ISSUE THREAD

**Issue by cocuana** [morrownr/rtl8852bu#5]
Hi,

I've compiled this driver to use a Zyxel NWD7605, but it didn't work.

For now I'm using this device with this version of the driver https://github.com/realtek-lunix/RTL8852BU_RTL8832BU_WiFi_linux

The result of lsusb is: ID 0586:3428 ZyXEL Communications Corp. 802.11ax WLAN Adapter
The link to the presentation of the adapter is https://www.zyxel.com/global/en/products/wifi-extender/dual-band-wireless-ax1800-usb-adapter-nwd7605

I'll be very grateful if you include, if possible, this device in this driver. 

Best regards,

José Fonseca

**Comment by morrownr** [comment]
Hola Jose,

Patch applied. You can update and recompile with the following commands:

$ git pull
$ sudo sh install-driver.sh

Let me know how it goes and this driver has had very little testing so a report would be nice to have.

@morrownr

**Comment by cocuana** [comment]
Hi,
I recompiled the driver and unhappily the driver load but I have no connectivity.
My environment is LinuxMint 21.2, kernel 5.19.0-50 on a MacbookPro8,1
I attach some files, I hope to help identify the issue.
Best regards,


[dkms_status_8852bu.txt](https://github.com/morrownr/rtl8852bu/files/12226312/dkms_status_8852bu.txt)
[lsmod_8852bu.txt](https://github.com/morrownr/rtl8852bu/files/12226313/lsmod_8852bu.txt)
[lsmod_all.txt](https://github.com/morrownr/rtl8852bu/files/12226314/lsmod_all.txt)
[modinfo_8852bu.txt](https://github.com/morrownr/rtl8852bu/files/12226315/modinfo_8852bu.txt)
[8852bu (copy).conf.txt](https://github.com/morrownr/rtl8852bu/files/12226338/8852bu.copy.conf.txt)

**Comment by cocuana** [comment]
Hi,

I also attach a file with modinfo with the driver currently workingd v1.15.7-112

The main difference  is here:
alias:          usb:v0B05p1A62d*dc*dsc*dp*icFFiscFFipFFin*
alias:          usb:v0586p3428d*dc*dsc*dp*icFFiscFFipFFin*
alias:          usb:v0BDApA85Bd*dc*dsc*dp*icFFiscFFipFFin*
alias:          usb:v0BDApB85Ad*dc*dsc*dp*icFFiscFFipFFin*
alias:          usb:v0BDApB852d*dc*dsc*dp*icFFiscFFipFFin*
alias:          usb:v0BDApB83Ad*dc*dsc*dp*icFFiscFFipFFin*
alias:          usb:v0BDApB832d*dc*dsc*dp*icFFiscFFipFFin*

vs

alias:          usb:v0BDApA85Bd*dc*dsc*dp*icFFiscFFipFFin*
alias:          usb:v0BDApB85Ad*dc*dsc*dp*icFFiscFFipFFin*
alias:          usb:v0BDApB852d*dc*dsc*dp*icFFiscFFipFFin*
alias:          usb:v0BDApB83Ad*dc*dsc*dp*icFFiscFFipFFin*
alias:          usb:v0BDApB832d*dc*dsc*dp*icFFiscFFipFFin*

I seems that v1.19.3 doesn't include ZyXEL USB VID:PID

I hope it helps.

Regards,
[modinfo_8852bu_v1_15_7_112.txt](https://github.com/morrownr/rtl8852bu/files/12226538/modinfo_8852bu_v1_15_7_112.txt)

**Comment by morrownr** [comment]
Did you run the following?

$ git pull
$ sudo sh install-driver.sh

If so, post the on screen output of install-driver.sh.

I added your VID/PID. The problem is that the old driver is still installed. I have code in install-driver.sh to detect and remove old drivers but the old driver was not removed.

**Comment by cocuana** [comment]
Hi,
Here attached is the result of:
git pull
sudo sh install-driver.sh
The behavior is the same:(
Regards,
[result_commands.txt](https://github.com/morrownr/rtl8852bu/files/12227315/result_commands.txt)

**Comment by cocuana** [comment]
Hi,
I think I found the issue! And you're right, the old driver was installed.
The issue is that after first installation when updating the new driver, the script doesn't update /usr/src/rtl8852bu-1.19.3.
I've updated it manually, recompile it with "sudo dkms build rtl8852bu/1.19.3" and then it loads and work fine!!
Is it something I've done wrong or is something wrong in any of the scripts or Makefile?
How can I help?
Regards,

**Comment by morrownr** [comment]
I am not feeling well today so it may be this evening before I am able to do much.

I do have some concerns you can look at:

You installed the driver in the following directory:

/media/eu/Utilities/Drivers/rtl8852bu

I'm not comfortable with that. You may see issues due to that location. I only test with the driver located somewhere in the home directory. The Installation Steps use a directory in the home directory. Recommend you use the Installation Steps.

I merged a patch this morning. It was the reason the driver did not remove your old driver. That should be working now. If you want to remove the current driver and try with the new, we can see.

**Comment by cocuana** [comment]
Hi,
It's working for now, I've tested it with several kernels and was working great. I'm now on kernel v5.15.x.xx, the one that came with LinuxMint 21.2
I'll follow your suggestion on new releases.
I hope you recover your health quickly!!
Best regards,
